title: "Strudel's Site"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
    style: compressed
    sass_dir: _sass

jekyll-minifier:
  uglifier_args:
    harmony: true
    output:
      comments: copyright