title: "Strudel's Site"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "default"

sass:
    style: compressed
    sass_dir: _sass

jekyll-minifier:
  uglifier_args:
    harmony: true
    output:
      comments: copyright

plugins:
  - jekyll-minifier

baseurl: ""
repository: "strudelfatpaws/strudelfatpaws.github.io"
url: "https://strudelfatpaws.github.io"