title: "Strudel's Site"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
    style: compressed
    sass_dir: _sass

exclude:
  - "/scripts"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor" # https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902

github: [metadata]

baseurl: ""
repository: "strwdyl/strwdyl.github.io"
url: "https://strwdyl.github.io"